### ISSUE TITLE
用DW1820A需要刷BIOS吗？

### ISSUE THREAD

**Issue by judyww** [FuckDoctors/IdeaPad-720s-13.3IKB#1]
DW1820A需要刷新BIOS吗，DW1560联想白名单版的有点贵

**Comment by FuckDoctors** [comment]
不需要刷BIOS，只有很老的笔记本才有白名单一说。
或者买联想版的DW1820A。

**Comment by judyww** [comment]
> 不需要刷BIOS，只有很老的笔记本才有白名单一说。
> 或者买联想版的DW1820A。

感谢，已经上车DW1820A

**Comment by FuckDoctors** [comment]
> > 不需要刷BIOS，只有很老的笔记本才有白名单一说。
> > 或者买联想版的DW1820A。
> 
> 感谢，已经上车DW1820A

上这车，需要有心里准备，蓝牙问题提多的，不过最近有解决方案了，不过我试了不行。。。
DW1820A型号太多了。。
