### ISSUE TITLE
关于网卡DW1820a的问题

### ISSUE THREAD

**Issue by TimonYY** [FuckDoctors/IdeaPad-720s-13.3IKB#10]
兄弟能说下你的DW1820a屏蔽了哪几个针脚吗？或者有没有网卡的具体版本号，怕买错了到时候驱动不上就麻烦了 某宝上搜到有三个型号分别是096JNT, 08PKF4和0VM3T3, 不知道你用的是哪种型号？
黑锅小兵的blog显示屏蔽中间的5根，网上有说屏蔽金手指的，不知道到底是哪一种呢

**Comment by TimonYY** [comment]
另外不知道DW1560怎么样，蓝牙问题会不会好一点 没有看到有人在720s上用的 在考虑1820a还是1560

**Comment by FuckDoctors** [comment]
感觉0VM3T3是最好的，但是我买的标签显示0VM3T3，但实际不是。。。估计是096那个，所以蓝牙不好用
DW1560不了解，性价比不高，所以不关注。

是屏蔽5个针脚，当时看的是这个：
https://osxlatitude.com/forums/topic/11540-dw1820a-the-general-troubleshooting-thread/?do=findComment&comment=91179

另外，据说禁用ASPM之后可以不用屏蔽了，你可以试试。

**Comment by TimonYY** [comment]
感谢，已经订了DW1820a, 准备用来试一试
请问禁用ASPM具体怎么操作，网上有说直接给bios打补丁的，感觉有风险，有没有黑果电源补丁或者修改电源参数之类安全一点的办法？

**Comment by TimonYY** [comment]
> 感谢，已经订了DW1820a, 准备用来试一试
> 请问禁用ASPM具体怎么操作，网上有说直接给bios打补丁的，感觉有风险，有没有黑果电源补丁或者修改电源参数之类安全一点的办法？

ASPM方法爬到了这个贴https://www.tonymacx86.com/threads/the-solution-dell-dw1820a-broadcom-bcm94350zae-macos-15.288026/ 
等网卡到了我试试

**Comment by TimonYY** [comment]
前来汇报一下。
今天收到了DW1820a的08PKF4版本，设置pci-aspm-default之后没有屏蔽针脚，WiFi驱动成功，双频正常。蓝牙在用了小兵的kexts之后也驱动成功，目前用Airpods测试了接近2小时，没有出现蓝牙断开的情况。Sidecar, Airdrop和Handoff都正常。
