### ISSUE TITLE
请问下声卡是怎么驱动的呢

### ISSUE THREAD

**Issue by iqoug** [FuckDoctors/IdeaPad-720s-13.3IKB#12]
尝试了好多id注入，都没用都是找不到设备，小喇叭灰色，请问是要自己编译驱动吗

**Comment by FuckDoctors** [comment]
不是自己编译，使用layout-id: 22。
看看声卡是不是同一个型号的，路径对不对。
https://github.com/FuckDoctors/ideapad-720s-13IKB/blob/master/EFI/CLOVER/config.plist#L312
