### ISSUE TITLE
cpu变频的教程能否提供下呢

### ISSUE THREAD

**Issue by iqoug** [FuckDoctors/IdeaPad-720s-13.3IKB#13]
蟹蟹～

**Comment by FuckDoctors** [comment]
设置好`plugin-type`就能开启原生变频了。
可以使用`CPUFriend`定制变频数据。
https://github.com/FuckDoctors/ideapad-720s-13ikb-oc#%E9%A9%B1%E5%8A%A8%E7%8A%B6%E5%86%B5

更多详情请去远景搜一下。
