### ISSUE TITLE
10.15.6 (19G2021)系统下编译dsdt.dst报错

### ISSUE THREAD

**Issue by iqoug** [FuckDoctors/IdeaPad-720s-13.3IKB#15]
用clover f4提取的aml 反编译得到dsdt.dsl后修改  再编译报错
系统：10.15.6 (19G2021)
请大佬帮忙看看
感谢

**Comment by iqoug** [comment]
以下是maciasl 编译的报错日志：
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(2773) : warning  3073 - Multiple types (Device object requires either a _HID or _ADR, but not both)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(4457) : warning  3115 - Not all control paths return a value (THDS)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(5315) : warning  3115 - Not all control paths return a value (GPEH)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(5470) : warning  3115 - Not all control paths return a value (GPEH)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(5519) : warning  3115 - Not all control paths return a value (_PS0)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(5561) : warning  3115 - Not all control paths return a value (_PS3)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(5618) : warning  3115 - Not all control paths return a value (_PS0)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(5631) : warning  3115 - Not all control paths return a value (_PS2)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(5644) : warning  3115 - Not all control paths return a value (_PS3)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(6503) : warning  3115 - Not all control paths return a value (GPEH)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(6551) : warning  3115 - Not all control paths return a value (GPEH)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(13190) : warning  3115 - Not all control paths return a value (RPON)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(13241) : warning  3115 - Not all control paths return a value (RPOF)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(13344) : warning  3115 - Not all control paths return a value (CNRS)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(13473) : warning  3115 - Not all control paths return a value (RPON)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(13524) : warning  3115 - Not all control paths return a value (RPOF)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(13627) : warning  3115 - Not all control paths return a value (CNRS)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(13756) : warning  3115 - Not all control paths return a value (RPON)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(13807) : warning  3115 - Not all control paths return a value (RPOF)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(13910) : warning  3115 - Not all control paths return a value (CNRS)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(14129) : warning  3115 - Not all control paths return a value (VMMH)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(14429) : warning  3073 - Multiple types (Device object requires either a _HID or _ADR, but not both)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(14487) : warning  3073 - Multiple types (Device object requires either a _HID or _ADR, but not both)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(14545) : warning  3073 - Multiple types (Device object requires either a _HID or _ADR, but not both)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(14603) : warning  3073 - Multiple types (Device object requires either a _HID or _ADR, but not both)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(14661) : warning  3073 - Multiple types (Device object requires either a _HID or _ADR, but not both)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(14719) : warning  3073 - Multiple types (Device object requires either a _HID or _ADR, but not both)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(14777) : warning  3073 - Multiple types (Device object requires either a _HID or _ADR, but not both)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(14834) : warning  3073 - Multiple types (Device object requires either a _HID or _ADR, but not both)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(14891) : warning  3073 - Multiple types (Device object requires either a _HID or _ADR, but not both)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(14964) : warning  3073 - Multiple types (Device object requires either a _HID or _ADR, but not both)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(15037) : warning  3073 - Multiple types (Device object requires either a _HID or _ADR, but not both)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(15331) : warning  3115 - Not all control paths return a value (_CRS)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(15331) : warning  3107 - Reserved method must return a value (Buffer required for _CRS)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(16417) : warning  3124 - Switch expression is not a static Integer/Buffer/String data type, defaulting to Integer
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(16675) : warning  3115 - Not all control paths return a value (TCRD)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(17114) : warning  3144 - Method Local is set but never used (Local2)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(17456) : warning  3115 - Not all control paths return a value (_BST)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(17456) : warning  3107 - Reserved method must return a value (Package required for _BST)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(17531) : warning  3133 - Unknown reserved name (_VPC)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(17538) : warning  3133 - Unknown reserved name (_CFG)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(17975) : warning  3115 - Not all control paths return a value (MHPF)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(18042) : warning  3115 - Not all control paths return a value (MHIF)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(18730) : warning  3115 - Not all control paths return a value (_PSR)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(18730) : warning  3107 - Reserved method must return a value (Integer required for _PSR)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(20291) : warning  3115 - Not all control paths return a value (SPL1)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(20701) : warning  3115 - Not all control paths return a value (VMON)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(20711) : warning  3115 - Not all control paths return a value (VMOF)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(21327) : warning  3115 - Not all control paths return a value (XTBT)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(22375) : warning  3168 - Legacy Processor() keyword detected. Use Device() keyword instead.
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(22376) : warning  3168 - Legacy Processor() keyword detected. Use Device() keyword instead.
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(22377) : warning  3168 - Legacy Processor() keyword detected. Use Device() keyword instead.
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(22378) : warning  3168 - Legacy Processor() keyword detected. Use Device() keyword instead.
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(22379) : warning  3168 - Legacy Processor() keyword detected. Use Device() keyword instead.
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(22380) : warning  3168 - Legacy Processor() keyword detected. Use Device() keyword instead.
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(22381) : warning  3168 - Legacy Processor() keyword detected. Use Device() keyword instead.
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(22382) : warning  3168 - Legacy Processor() keyword detected. Use Device() keyword instead.
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(22383) : warning  3168 - Legacy Processor() keyword detected. Use Device() keyword instead.
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(22384) : warning  3168 - Legacy Processor() keyword detected. Use Device() keyword instead.
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(22385) : warning  3168 - Legacy Processor() keyword detected. Use Device() keyword instead.
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(22386) : warning  3168 - Legacy Processor() keyword detected. Use Device() keyword instead.
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(22387) : warning  3168 - Legacy Processor() keyword detected. Use Device() keyword instead.
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(22388) : warning  3168 - Legacy Processor() keyword detected. Use Device() keyword instead.
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(22389) : warning  3168 - Legacy Processor() keyword detected. Use Device() keyword instead.
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(22390) : warning  3168 - Legacy Processor() keyword detected. Use Device() keyword instead.
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(23975) : error    6022 - Case value already specified
2020/9/2 上午1:11:42, Original Case value below:
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(23923) :
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(23979) : error    6022 - Case value already specified
2020/9/2 上午1:11:42, Original Case value below:
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(23959) :
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(24266) : error    6022 - Case value already specified
2020/9/2 上午1:11:42, Original Case value below:
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(24214) :
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(24270) : error    6022 - Case value already specified
2020/9/2 上午1:11:42, Original Case value below:
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(24250) :
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(24557) : error    6022 - Case value already specified
2020/9/2 上午1:11:42, Original Case value below:
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(24505) :
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(24561) : error    6022 - Case value already specified
2020/9/2 上午1:11:42, Original Case value below:
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(24541) :
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(24848) : error    6022 - Case value already specified
2020/9/2 上午1:11:42, Original Case value below:
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(24796) :
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(24852) : error    6022 - Case value already specified
2020/9/2 上午1:11:42, Original Case value below:
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(24832) :
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(25139) : error    6022 - Case value already specified
2020/9/2 上午1:11:42, Original Case value below:
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(25087) :
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(25143) : error    6022 - Case value already specified
2020/9/2 上午1:11:42, Original Case value below:
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(25123) :
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(25430) : error    6022 - Case value already specified
2020/9/2 上午1:11:42, Original Case value below:
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(25378) :
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(25434) : error    6022 - Case value already specified
2020/9/2 上午1:11:42, Original Case value below:
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(25414) :
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(25721) : error    6022 - Case value already specified
2020/9/2 上午1:11:42, Original Case value below:
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(25669) :
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(25725) : error    6022 - Case value already specified
2020/9/2 上午1:11:42, Original Case value below:
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(25705) :
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(26012) : error    6022 - Case value already specified
2020/9/2 上午1:11:42, Original Case value below:
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(25960) :
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(26016) : error    6022 - Case value already specified
2020/9/2 上午1:11:42, Original Case value below:
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(25996) :
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(26303) : error    6022 - Case value already specified
2020/9/2 上午1:11:42, Original Case value below:
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(26251) :
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(26307) : error    6022 - Case value already specified
2020/9/2 上午1:11:42, Original Case value below:
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(26287) :
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(26594) : error    6022 - Case value already specified
2020/9/2 上午1:11:42, Original Case value below:
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(26542) :
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(26598) : error    6022 - Case value already specified
2020/9/2 上午1:11:42, Original Case value below:
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(26578) :
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(26885) : error    6022 - Case value already specified
2020/9/2 上午1:11:42, Original Case value below:
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(26833) :
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(26889) : error    6022 - Case value already specified
2020/9/2 上午1:11:42, Original Case value below:
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(26869) :
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(27176) : error    6022 - Case value already specified
2020/9/2 上午1:11:42, Original Case value below:
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(27124) :
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(27180) : error    6022 - Case value already specified
2020/9/2 上午1:11:42, Original Case value below:
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(27160) :
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(27467) : error    6022 - Case value already specified
2020/9/2 上午1:11:42, Original Case value below:
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(27415) :
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(27471) : error    6022 - Case value already specified
2020/9/2 上午1:11:42, Original Case value below:
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(27451) :
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(27758) : error    6022 - Case value already specified
2020/9/2 上午1:11:42, Original Case value below:
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(27706) :
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(27762) : error    6022 - Case value already specified
2020/9/2 上午1:11:42, Original Case value below:
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(27742) :
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(28049) : error    6022 - Case value already specified
2020/9/2 上午1:11:42, Original Case value below:
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(27997) :
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(28053) : error    6022 - Case value already specified
2020/9/2 上午1:11:42, Original Case value below:
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(28033) :
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(28340) : error    6022 - Case value already specified
2020/9/2 上午1:11:42, Original Case value below:
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(28288) :
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(28344) : error    6022 - Case value already specified
2020/9/2 上午1:11:42, Original Case value below:
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(28324) :
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(28631) : error    6022 - Case value already specified
2020/9/2 上午1:11:42, Original Case value below:
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(28579) :
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(28635) : error    6022 - Case value already specified
2020/9/2 上午1:11:42, Original Case value below:
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(28615) :
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(28922) : error    6022 - Case value already specified
2020/9/2 上午1:11:42, Original Case value below:
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(28870) :
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(28926) : error    6022 - Case value already specified
2020/9/2 上午1:11:42, Original Case value below:
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(28906) :
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(29213) : error    6022 - Case value already specified
2020/9/2 上午1:11:42, Original Case value below:
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(29161) :
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(29217) : error    6022 - Case value already specified
2020/9/2 上午1:11:42, Original Case value below:
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(29197) :
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(29504) : error    6022 - Case value already specified
2020/9/2 上午1:11:42, Original Case value below:
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(29452) :
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(29508) : error    6022 - Case value already specified
2020/9/2 上午1:11:42, Original Case value below:
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(29488) :
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(33577) : warning  3115 - Not all control paths return a value (DB2H)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(33613) : warning  3115 - Not all control paths return a value (MBGS)
2020/9/2 上午1:11:42, iASLxtgkJz.dsl(33635) : warning  3115 - Not all control paths return a value (ADBG)
2020/9/2 上午1:11:42, ASL Input:     iASLxtgkJz.dsl - 1107455 bytes  16959 keywords  34073 source lines
2020/9/2 上午1:11:42, Compilation failed. 40 Errors, 68 Warnings, 85 Remarks
2020/9/2 上午1:11:42, No AML files were generated due to compiler error(s)

**Comment by iqoug** [comment]
[DSDT.dsl.zip](https://github.com/FuckDoctors/ideapad-720s-13IKB/files/5157831/DSDT.dsl.zip)

**Comment by FuckDoctors** [comment]
你是dsdt和ssdt要联合反编译的吗？
联合反编译基本不会出错。
我是在win10下反编译的。
把dsdt和ssdt放一块，然后使用`iasl -da -dl *.aml`。
详情参考：http://bbs.pcbeta.com/viewthread-1475332-1-1.html

**Comment by iqoug** [comment]
> 你是dsdt和ssdt要联合反编译的吗？
> 联合反编译基本不会出错。
> 我是在win10下反编译的。
> 把dsdt和ssdt放一块，然后使用`iasl -da -dl *.aml`。
> 详情参考：http://bbs.pcbeta.com/viewthread-1475332-1-1.html

是联合反编译的，修改dsdt.dsl以后再编译生成dsdt.aml文件时报错

ps：远景挂了...-。-！

**Comment by FuckDoctors** [comment]
等周末看看吧，我周末才能用笔记本

**Comment by iqoug** [comment]
问题已解决，是iasl的版本造成的，必须使用iasl61
