### ISSUE TITLE
大神你好，我也是日版720s13，请问刷黑苹果容易损坏主板吗？你的经验很惨痛啊

### ISSUE THREAD

**Issue by Neopy2020** [FuckDoctors/IdeaPad-720s-13.3IKB#16]
配置贴一下，我小白，麻烦指导下看能不能直接用你的efi刷
型号 Lenovo ideapad 720S-13IKB
cpu 8250u
主板 lnvnb161216
bios 6mcn28ww
内存 SK Hynix 8g x1
显示器 LG Philips LP133WF4-SPB1

**Comment by FuckDoctors** [comment]
应该没问题，不用动主板，我是为了刷BIOS的高级菜单。
黑苹果不用开高级菜单也可以。
dsdt最好先别直接用，需要自己定制。
可以用oc版，仅用ssdt，不用dsdt。

**Comment by Neopy2020** [comment]
> 应该没问题，不用动主板，我是为了刷BIOS的高级菜单。
> 黑苹果不用开高级菜单也可以
> 。dsdt最好先别直接用，需要自己定制。
> 可以用oc版，仅用ssdt，不用dsdt。

大神可不可以加个WeChat，有个人联络我变砖了也有帮助

**Comment by Neopy2020** [comment]
> 应该没问题，不用动主板，我是为了刷BIOS的高级菜单。
> 黑苹果不用开高级菜单也可以
> 。dsdt最好先别直接用，需要自己定制。
> 可以用oc版，仅用ssdt，不用dsdt。

用oc版更稳定是吧

**Comment by Neopy2020** [comment]
> 应该没问题，不用动主板，我是为了刷BIOS的高级菜单。
> 黑苹果不用开高级菜单也可以
> 。dsdt最好先别直接用，需要自己定制。
> 可以用oc版，仅用ssdt，不用dsdt。

不用你的dsdt，装好后我自己再定制个dsdt吗

**Comment by Neopy2020** [comment]
> 应该没问题，不用动主板，我是为了刷BIOS的高级菜单。
> 黑苹果不用开高级菜单也可以
> 。dsdt最好先别直接用，需要自己定制。
> 可以用oc版，仅用ssdt，不用dsdt。

请问如果中途失败了，会不会有损坏主板机器完全变砖的可能

**Comment by FuckDoctors** [comment]
装系统基本上都不会损坏硬件。
我那是直接拆机，用编程器直接操作BIOS芯片了
原来有windows的话，操作不当，可能会影响windows的EFI，使用WinPE修复一下引导就可以了

**Comment by Neopy2020** [comment]
> 装系统基本上都不会损坏硬件。
> 我那是直接拆机，用编程器直接操作BIOS了芯片
> 原来有窗户的话，操作不当，可能会影响窗户的EFI，WinPE的使用修复一下引导就可以了

感谢你的分享，我已经成功了，很简单顺利的过程，除了网卡一切驱动都正常
