### ISSUE TITLE
老哥，能请教一下安装的问题吗

### ISSUE THREAD

**Issue by quenstyLai** [FuckDoctors/IdeaPad-720s-13.3IKB#17]
![16e786099e689aa6.jpg](https://user-images.githubusercontent.com/35103072/110458771-1e6ac500-8107-11eb-8942-81275c7844d4.jpg)
我进u盘的oc引导后，没有安装的选项

**Comment by FuckDoctors** [comment]
OC配置是用的我的配置文件吗？
还是用的你的安装镜像里的配置？

**Comment by quenstyLai** [comment]
> OC配置是用的我的配置文件吗？
> 还是用的你的安装镜像里的配置？

用的你的oc,已经解决了，多谢老哥

**Comment by FuckDoctors** [comment]
> > OC配置是用的我的配置文件吗？
> > 还是用的你的安装镜像里的配置？
> 
> 用的你的oc,已经解决了，多谢老哥

咋解决的也写一下吧，方便别人^_^

**Comment by quenstyLai** [comment]
交给别人解决的🌝🌝

**Comment by FuckDoctors** [comment]
好吧，OC配置感觉没问题，只要放了相应的.efi驱动应该没问题
