### ISSUE TITLE
同型号 i7-8550U, 4K UHD屏, 合盖黑屏后, 唤醒, 屏幕闪烁

### ISSUE THREAD

**Issue by iamchating** [FuckDoctors/IdeaPad-720s-13.3IKB#2]
我是参考您的EFI改的, 效果挺好
ideapad-720s-13IKB,  i7-8550U, 4K UHD屏(美版高配型号)
直接把您plist里面Device-显卡部分抄到我的plist里面 加速完美

现在遇到 合盖黑屏后, 唤醒, 屏幕闪烁的问题 不知道您是否遇到过,  谢谢

**Comment by FuckDoctors** [comment]
不好意思，没注意看issues。
屏幕闪烁的问题，没遇到过。

**Comment by MilineChen** [comment]
> 我是参考您的EFI改的, 效果挺好
> ideapad-720s-13IKB, i7-8550U, 4K UHD屏(美版高配型号)
> 直接把您plist里面Device-显卡部分抄到我的plist里面 加速完美
> 
> 现在遇到 合盖黑屏后, 唤醒, 屏幕闪烁的问题 不知道您是否遇到过, 谢谢

请问下高配版的显示屏是什么型号的？之前一直查找都找不到

**Comment by iamchating** [comment]
> > 我是参考您的EFI改的, 效果挺好
> > ideapad-720s-13IKB, i7-8550U, 4K UHD屏(美版高配型号)
> > 直接把您plist里面Device-显卡部分抄到我的plist里面 加速完美
> > 现在遇到 合盖黑屏后, 唤醒, 屏幕闪烁的问题 不知道您是否遇到过, 谢谢
> 
> 请问下高配版的显示屏是什么型号的？之前一直查找都找不到


AU Optronics B133ZAN01.1 [13.3" LCD]

**Comment by FuckDoctors** [comment]
偶然看到的资料，供参考：
更换4k屏后会黑屏进不去桌面
https://github.com/kirainmoe/hasee-tongfang-macos/issues/33
https://hackintosh.kirainmoe.com/ying-jian-xiang-guan/geng-huan-4k-ping-mu-hou-wu-fa-jin-ru-xi-tong-de-jie-jue-fang-an

**Comment by iamchating** [comment]
> 偶然看到的资料，供参考：
> 更换4k屏后会黑屏进不去桌面
> [kirainmoe/hasee-tongfang-macos#33](https://github.com/kirainmoe/hasee-tongfang-macos/issues/33)
> https://hackintosh.kirainmoe.com/ying-jian-xiang-guan/geng-huan-4k-ping-mu-hou-wu-fa-jin-ru-xi-tong-de-jie-jue-fang-an

谢谢您过了这么久还记得我的事情，可惜我机器已经给别人用了，没法验证了
再次表示感谢
