### ISSUE TITLE
楼主拔电盒盖掉电厉害吗 i7-8550U 版本

### ISSUE THREAD

**Issue by jiang123574** [FuckDoctors/IdeaPad-720s-13.3IKB#3]
楼主拔电关机掉电厉害吗 ，我拔电盒盖一晚上电差不多得掉完，感觉没有进入省电状态

**Comment by FuckDoctors** [comment]
没试过，可能是睡眠不好。
刚升了10.15，没法试了。。10.15一直重启，还没解决，出差在外，没U盘，也没法全新安装。。

10/14 更新：
搞了一天，10.15终于好了~

**Comment by FuckDoctors** [comment]
Catalina 10.15下试了一下，同样，一晚上差不多掉完。。

10/14 22:10更新
加入SSDT-GPRW.aml试试

**Comment by iamchating** [comment]
> 楼主拔电关机掉电厉害吗 ，我拔电盒盖一晚上电差不多得掉完，感觉没有进入省电状态

请问你的i7版本是1080屏还是4K屏,  有遇到过唤醒屏幕闪烁的问题吗

**Comment by jiang123574** [comment]
1080P 没有闪烁问题

**Comment by FuckDoctors** [comment]
> Catalina 10.15下试了一下，同样，一晚上差不多掉完。。
> 
> 10/14 22:10更新
> 加入SSDT-GPRW.aml试试

使用SSDT-GPRW.aml后，去掉网络唤醒，10小时睡眠掉电4%。

**Comment by jiang123574** [comment]
> > Catalina 10.15下试了一下，同样，一晚上差不多掉完。。
> > 10/14 22:10更新
> > 加入SSDT-GPRW.aml试试
> 
> 使用SSDT-GPRW.aml后，去掉网络唤醒，10小时睡眠掉电4%。

现在的情况是，使用触摸板驱动会在启动过程中重启  10.15系统

**Comment by FuckDoctors** [comment]
> 现在的情况是，使用触摸板驱动会在启动过程中重启 10.15系统

刚开始我也遇到10.15重启的事，后来各种尝试，现在正常了，使用了最新的驱动也不行，修改了config就可以了。
去掉了EHC1和EHC2的补丁，以及External icons patch的补丁就可以了。
我的触摸板驱动没问题，每次升级后不能使用，重建缓存重启后就会正常了。

**Comment by FuckDoctors** [comment]
睡眠没问题了，所以关闭issue了
