### ISSUE TITLE
10.15发现新问题

### ISSUE THREAD

**Issue by jiang123574** [FuckDoctors/IdeaPad-720s-13.3IKB#4]
10.15发现新的问题了， 电池不显示，使用触摸板驱动会直接重启

**Comment by jiang123574** [comment]
用楼主的efi，连10.14.6都安装不成功了，卡在进度条最后

**Comment by FuckDoctors** [comment]
拿掉触摸板驱动正常吗？
我没使用触摸板的SSDT，而是直接修改了DSDT，这俩配套使用的。
使用精简后的config试试，一开始别加载那么多。
https://github.com/FuckDoctors/ideapad-720s-13IKB/blob/7240950b0b4775cdcf2dc661b13acc2d16b3a77b/EFI/CLOVER/config.plist

**Comment by jiang123574** [comment]
拿掉触摸板驱动后正常，然后电池图标不显示，电池电量显示不正确，显示0%

**Comment by FuckDoctors** [comment]
我电池没做补丁，使用SMCBatteryManager.kext就可以了。
使用最新的VirtualSMC.kext及配套Sensors驱动。

**Comment by jiang123574** [comment]
> 我电池没做补丁，使用SMCBatteryManager.kext就可以了。
> 使用最新的VirtualSMC.kext及配套Sensors驱动。

今天重新全新安装了一次，居然电池和触摸板都好了，成功完美安装
