### ISSUE TITLE
能共享一个最新的EFI包吗? 

### ISSUE THREAD

**Issue by iamchating** [FuckDoctors/IdeaPad-720s-13.3IKB#5]
我把您的EFI文件夹直接扔在我的盘的EFI下, 按您的做法设好BIOS, 直接起不来了,  看到WIndows的恢复蓝色界面

**Comment by FuckDoctors** [comment]
master分支上就是最新的东西，现在时10.15的，10.14的看其他分支。
dsdt最好别直接用，哪怕同款机器，差分对比一下dsdt，然后合并一下。

**Comment by xiaominglei001** [comment]
> master分支上就是最新的东西，现在时10.15的，10.14的看其他分支。
> dsdt最好别直接用，哪怕同款机器，差分对比一下dsdt，然后合并一下。

同样的问题，直接黑屏重启，请问下怎么差分对比合并dsdt，百度找不到，有教程推荐下吗？万谢！

**Comment by FuckDoctors** [comment]
> > master分支上就是最新的东西，现在时10.15的，10.14的看其他分支。
> > dsdt最好别直接用，哪怕同款机器，差分对比一下dsdt，然后合并一下。
> 
> 同样的问题，直接黑屏重启，请问下怎么差分对比合并dsdt，百度找不到，有教程推荐下吗？万谢！

DSDT，SSDT先拿掉试试，-v模式看看卡哪块。
都上传了dsl文件，使用差分工具对比一下自己Clover下按F4提取的文件。
dsdt，ssdt处理可以看网上的其他教程。或者我链接的那个dsdt，ssdt联合反编译处理。

**Comment by xiaominglei001** [comment]
直接用https://github.com/dragonflylee/Yoga-730-hackintosh 这里的EFI就好了，把声卡改为22，看到远景评论里提到的因为机器参数很相近，http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1817262&highlight=720s  这个可能是热补丁，不需要拆分对比DSDT，目前除了网卡蓝牙要换，其它都好。

**Comment by FuckDoctors** [comment]
> 直接用https://github.com/dragonflylee/Yoga-730-hackintosh 这里的EFI就好了，把声卡改为22，看到远景评论里提到的因为机器参数很相近，http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1817262&highlight=720s 这个可能是热补丁，不需要拆分对比DSDT，目前除了网卡蓝牙要换，其它都好。

好了就行。
我的声卡就是用的22，readme中提到了，自己对比codec确定出来的，使用hacktool的生成的Patch。远景帖子里的`zhbchwin`是本人。
触摸板根据官方资料修改的DSDT，小太阳修改了DSDT，其他未修改，现在这两个也都有SSDT了，可以搜索其他人的资料。
