### ISSUE TITLE
同型号 海力士内存固态 需要修改文件么

### ISSUE THREAD

**Issue by xc233** [FuckDoctors/IdeaPad-720s-13.3IKB#6]
大佬您好，直接替换efi没安装成功
请问海力士版本是否有要修改的文件 非常感谢

**Comment by FuckDoctors** [comment]
内存部分的DSDT虽然有些差别，但不影响，现在的DSDT虽然是三星内存提取的，但是我现在用的海力士的内存，运行没啥问题就没再更换DSDT。
一开始尽量别放太多东西，dsdt，ssdt先不要放，-v模式看看哪里出问题了。
