### ISSUE TITLE
每次开机显示no asix usb dongle found那个提示，有什么办法去掉吗

### ISSUE THREAD

**Issue by xiaominglei001** [FuckDoctors/IdeaPad-720s-13.3IKB#7]
如题，不知道是不是bios设置的关系，每次走这段提示有点耗时。
![1218388207](https://user-images.githubusercontent.com/7384014/68987780-36f70200-0868-11ea-9fec-e4c7469aed8d.jpg)

**Comment by FuckDoctors** [comment]
不清楚，没有这个我问题。

**Comment by FuckDoctors** [comment]
刚刚试网络启动时，出现了这个界面。
估计是你的启动顺序设了网络启动是第一个吧，修改下启动顺序
