### ISSUE TITLE
关于ideapad 720s 14IKB

### ISSUE THREAD

**Issue by ytm2004** [FuckDoctors/IdeaPad-720s-13.3IKB#8]
我的电脑是ideapad 720s 14IKB的，请问可不可以把13IKB的直接拿到我的电脑这里用？如果不可以的话，还要做什么修改？
P.S. 我在网上找了半天都没找到现成的ideapad 720s 14IKB的EFI文件……

**Comment by FuckDoctors** [comment]
不清楚14的配置，dsdt去掉，usb，type-c，雷电3的ssdt驱动拿掉试试。
自己慢慢试试，看看哪有问题。

**Comment by ytm2004** [comment]
想用U盘给电脑安装黑苹果，用了这里面的clover文件，重启电脑后只显示了windows系统启动选项，没看到安装macos的选项，这该咋整

**Comment by FuckDoctors** [comment]
> 想用U盘给电脑安装黑苹果，用了这里面的clover文件，重启电脑后只显示了windows系统启动选项，没看到安装macos的选项，这该咋整

安装完了没显示？
使用Clover文件夹，确保有HFS.efi驱动。
去掉GUI\Custom\Entries和GUI\Hide，看看能不能显示。

**Comment by TimonYY** [comment]
> 我的电脑是ideapad 720s 14IKB的，请问可不可以把13IKB的直接拿到我的电脑这里用？如果不可以的话，还要做什么修改？
> P.S. 我在网上找了半天都没找到现成的ideapad 720s 14IKB的EFI文件……

请问你的问题解决了吗？ 我也是14寸的720s....

**Comment by TimonYY** [comment]
我的14寸720s比13寸的多了MX150独显，然后是i7-8550U的处理器，UHD620显卡，用了你的这个EFI，根据你的建议，开启Legacy Support进步了Clover, 用UEFI模式可以进入CLover但是报AppleNVMe的错误，请问你知道需要怎么修改吗？

**Comment by FuckDoctors** [comment]
> 我的14寸720s比13寸的多了MX150独显，然后是i7-8550U的处理器，UHD620显卡，用了你的这个EFI，根据你的建议，开启Legacy Support进步了Clover, 用UEFI模式可以进入CLover但是报AppleNVMe的错误，请问你知道需要怎么修改吗？

不知道，根据错误信息搜一下吧，是不是macOS不兼容的ssd。

**Comment by TimonYY** [comment]
搞定了，昨天拆开电脑偶然间发现硬盘居然是PM981, 我一直记得是PM961来着。。。还被这困扰了两天，换了张盘一遍通过哎哟我去....

**Comment by FuckDoctors** [comment]
PM981需要特殊处理的，搞定了就行。
